version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - ${TRANSMISSION_CONFIG_DIR}:/config
      - ${TRANSMISSION_DOWNLOADS_DIR}:/downloads
      - ${TRANSMISSION_WATCH_DIR}:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ${SONARR_CONFIG_DIR}:/config
      - ${SONARR_TV_DIR}:/tv
      - ${SONARR_DOWNLOADS_DIR}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ${HOMARR_CONFIGS_DIR}:/app/data/configs
      - ${HOMARR_ICONS_DIR}:/app/public/icons
    ports:
      - '7575:7575'
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Warsaw
    ports:
      - 5055:5055
    volumes:
      - ${OVERSEERR_CONFIG_DIR}:/app/config
    restart: unless-stopped
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Warsaw
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
      - ADVERTISE_IP=http://${PLEX_ADVERTISE_IP}:32400/
    hostname: ${PLEX_HOSTNAME}
    volumes:
      - ${PLEX_CONFIG_DIR}:/config
      - ${PLEX_TRANSCODE_DIR}:/transcode
      - ${PLEX_MEDIA_DIR}:/data
